/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ww_sotest_Dynamic */

#ifndef _Included_com_ww_sotest_Dynamic
#define _Included_com_ww_sotest_Dynamic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ww_sotest_Dynamic
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ww_sotest_Dynamic_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
